######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 8 14:06:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += console

# Input
HEADERS += blackjack.h blackjack_canvas.h deck.h strategy.h
SOURCES += blackjack.cpp blackjack_canvas.cpp deck.cpp main.cpp strategy.cpp
RESOURCES += cards.qrc
CONFIG += console
